spring:
  application:
    name: transaction-engine
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mapping: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never